name: Notify Discord on Workflow Completion

on:
  workflow_run:
    workflows: ['Lint Code']
    types:
      - completed

permissions:
  pull-requests: read

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Info
        id: get_pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(echo '${{ toJson(github.event.workflow_run.pull_requests) }}' | jq '.[0].number')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

          if [ -z "$PR_NUMBER" ] || [ "$PR_NUMBER" = "null" ]; then
            echo "No PR found."
            echo "IS_DRAFT=false" >> $GITHUB_ENV
            exit 0
          fi

          PR_API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER"
          IS_DRAFT=$(curl -s -H "Authorization: token $GH_TOKEN" $PR_API_URL | jq '.draft')
          echo "IS_DRAFT=$IS_DRAFT" >> $GITHUB_ENV

      - name: Notify Discord
        if: env.IS_DRAFT == 'false'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          NAME: ${{ github.event.workflow_run.name }}
          STATUS: ${{ github.event.workflow_run.conclusion }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
        run: |
          ICON="✅"
          if [ "$STATUS" != "success" ]; then
            ICON="❌"
          fi

          PR_URL="https://github.com/${REPO}/pull/${PR_NUMBER}"
          STATUS_MESSAGE=""

          if [ "$STATUS" = "success" ]; then
            STATUS_MESSAGE="PR is ready for review!"
          else
            STATUS_MESSAGE="PR build failed, please check the workflow logs."
          fi

          MESSAGE="${ICON} Workflow **${NAME}** completed with status: **${STATUS}**\n${STATUS_MESSAGE}\n🔗 PR: ${PR_URL}"

          curl -H "Content-Type: application/json" \
              -X POST \
              -d "{\"content\": \"$MESSAGE\"}" \
              $DISCORD_WEBHOOK
