name: Notify Discord on Workflow Completion

on:
  workflow_run:
    workflows: ['Lint Code']
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          NAME: ${{ github.event.workflow_run.name }}
          STATUS: ${{ github.event.workflow_run.conclusion }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
        run: |
          ICON="✅"
          if [ "$STATUS" != "success" ]; then
            ICON="❌"
          fi

          if [ -n "$PR_NUMBER" ]; then
            PR_URL="https://github.com/${REPO}/pull/${PR_NUMBER}"

            STATUS_MESSAGE=""
            if [ "$STATUS" = "success" ]; then
              STATUS_MESSAGE="PR is ready for review!"
            else
              STATUS_MESSAGE="PR build failed, please check the workflow logs."
            fi

            MESSAGE="${ICON} Workflow **${NAME}** completed with status: **${STATUS}**\n${STATUS_MESSAGE}\n🔗 PR: ${PR_URL}"

            curl -H "Content-Type: application/json" \
                -X POST \
                -d "{\"content\": \"$MESSAGE\"}" \
                $DISCORD_WEBHOOK
          else
            echo "No PR found, skipping Discord notification."
          fi
